### ISSUE TITLE
"Are you sure" and still running while game is in focus.

### ISSUE THREAD

**Issue by ghost** [rgrams/ross_project_timer#1]
I was originally going to post this as a reply in the issue I made on the main Godot page, but felt it would be better here.

I think there should be an options to allow the timer to stay unpaused when you are not in the Godot editor window, so that it can time while your game is running. Maybe there is some way to do this where only if the game is in focus keep counting? (I'm not sure, don't know much about editor plugins).

Another improvement could be to add an "are you sure" popup when you click reset so that you don't accidentally reset your timer.

Edit: I realize both of these are negligible because of the "Add time" feature, but it would be more for convince than anything else.

**Comment by rgrams** [comment]
Good points, thanks! A confirm popup for resetting is a good idea. I thought about doing it before but was too lazy. The add time feature does let you put the time back if you reset it by mistake, but I'm sure there will be times when you forget how much time you had. Easy enough to fix. 

Hmm, that's a good point about counting "playtest" time. I'm not sure how to do that, but I'll look into it.

**Comment by rgrams** [comment]
Well I haven't figured out any way to keep the time running while you play the game from the editor, but I just added an option for it to not pause when you switch windows. So you can use it either way.  24a48eac78eeb0fb27e839f5e8fd9797b3ed1021

**Comment by ghost** [comment]
That works great! Thank you.
