### ISSUE TITLE
Update spinner goes crazy when timer is paused

### ISSUE THREAD

**Issue by akien-mga** [rgrams/ross_project_timer#2]
As the title says. In normal mode the spinner changes one per second, as it should, but when you pause the project timer, it spins continuously.

**Comment by rgrams** [comment]
Would that be because there is an animation playing? To be honest I never understood what that spinner was for, though I guess the tooltip is pretty explicit now that I look at it.

**Comment by akien-mga** [comment]
Or right, now I see there is a fading animation, so that's normal. The editor has to redraw all the time for the animation.
The animation is cool so it's nice to have it by default IMO. There could be an option to disable animation on pause for those who fear wasting CPU... but at the same time such a plugin is not really meant to be paused that much :p

**Comment by rgrams** [comment]
OK. Yeah, you're right. When paused it shows up on mine as using 1-3% CPU. And even 1% every other second when it's minimized. But it only occasionally shows 1% when it's actually ticking. I'll fiddle around with a static way of showing that it's paused.

**Comment by akien-mga** [comment]
I guess a "paused" icon (like :pause_button:) would do the trick.
